// Code generated by "stringer -type=ZeroEventsName"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ZeroEventGroupMessage-0]
	_ = x[ZeroEventPrivateMessage-1]
	_ = x[ZeroEventGroupMute-2]
	_ = x[ZeroEventGroupRecalled-3]
	_ = x[ZeroEventFriendRecalled-4]
	_ = x[ZeroEventJoinGroup-5]
	_ = x[ZeroEventLeaveGroup-6]
	_ = x[ZeroEventMemberJoin-7]
	_ = x[ZeroEventMemberLeave-8]
	_ = x[ZeroEventMemberCardUpdated-9]
	_ = x[ZeroEventPermissionChanged-10]
	_ = x[ZeroEventJoinRequest-11]
	_ = x[ZeroEventFriendRequest-12]
	_ = x[ZeroEventNewFriend-13]
	_ = x[ZeroEventNotify-14]
	_ = x[ZeroEventGroupMessageReceipt-15]
	_ = x[ZeroEventLog-16]
	_ = x[ZeroEventDisconnect-17]
	_ = x[ZeroEventServerUpdated-18]
}

const _ZeroEventsName_name = "ZeroEventGroupMessageZeroEventPrivateMessageZeroEventGroupMuteZeroEventGroupRecalledZeroEventFriendRecalledZeroEventJoinGroupZeroEventLeaveGroupZeroEventMemberJoinZeroEventMemberLeaveZeroEventMemberCardUpdatedZeroEventPermissionChangedZeroEventJoinRequestZeroEventFriendRequestZeroEventNewFriendZeroEventNotifyZeroEventGroupMessageReceiptZeroEventLogZeroEventDisconnectZeroEventServerUpdated"

var _ZeroEventsName_index = [...]uint16{0, 21, 44, 62, 84, 107, 125, 144, 163, 183, 209, 235, 255, 277, 295, 310, 338, 350, 369, 391}

func (i ZeroEventsName) String() string {
	if i >= ZeroEventsName(len(_ZeroEventsName_index)-1) {
		return "ZeroEventsName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ZeroEventsName_name[_ZeroEventsName_index[i]:_ZeroEventsName_index[i+1]]
}
